feat:The workflow for mockup design and feasibility check , and added button in design request
efeoneAcademy/versa_system pull request #243
Opened 2024-12-16 09:23 UTC by avishna-avi

## Feature description
Create  a workflow for mockup design and added a button in the design request
## Solution description
- A workflow for mockup design and feasibility check is being created.  
- A "Go to Lead"  button is added to the Design Request form and it is visible only when the feasibility check is approved.
## Output
![image](https://github.com/user-attachments/assets/2b8d6e17-53fc-4408-b02e-c168c0b04d8e)
![image](https://github.com/user-attachments/assets/69068dcf-d8dd-4cf3-b7ce-32c9d95034ea)
![image](https://github.com/user-attachments/assets/5121c155-5694-44d8-ba24-b433e343b966)

## Areas affected and ensured
-New feature

## Is there any existing behavior change of other features due to this code change?
-No

## Was this feature tested on the browsers?
  - Mozilla Firefox

2024-12-16 11:31 UTC, SherinKR requested changes, later dismissed

2024-12-16 11:31 UTC, SherinKR commented on versa_system/hooks.py
> +    }
Use Workflow Action Master

2024-12-17 10:11 UTC, MhmdSinanKT requested changes
change fixtures of workflow action to workflow action master

2024-12-17 10:36 UTC, MhmdSinanKT approved these changes

2024-12-17 10:37 UTC, merged